version: "2"
linters:
  default: standard
  settings:
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
        - security
        - opinionated
        - diagnostic
    lll:
      line-length: 200
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofmt
    - goimports
